<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
	<!ELEMENT students (student+)>
	<!ELEMENT student (name,age,gender)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT gender (#PCDATA)>
]>
<students>
	<student>
		<name>mike</name>
		<age>20</age>
		<gender>male</gender>
	</student>
	<student>
		<name>jerry</name>
		<age>21</age>
		<gender>female</gender>
	</student>
</students>